//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYeni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.OduncKitaplar = new HashSet<OduncKitaplar>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> YazarID { get; set; }
        public string YayinYili { get; set; }
        public string SayfaSayisi { get; set; }
        public string Fiyat { get; set; }
        public string KayitYapan { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string DegisiklikYapan { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncKitaplar> OduncKitaplar { get; set; }
    }
}
